### ISSUE TITLE
[REVIEW] Add complete (if basic) usage example to docs homepage and README

### ISSUE THREAD

**Issue by ashiklom** [VEZY/PlantSimEngine.jl#32]
I suggest including 1-2 examples of complete usage on the README and documentation home page. Basically, what you've already done in `PlantBiophysics.jl`. 

For another good example, see [`SpeedyWeather.jl`](https://github.com/SpeedyWeather/SpeedyWeather.jl#example-use).

https://github.com/openjournals/joss-reviews/issues/5371

**Comment by VEZY** [comment]
Hey @ashiklom, thanks for the review. I added two basic examples to the [README](https://github.com/VEZY/PlantSimEngine.jl/blob/main/README.md) + the [landing page](https://vezy.github.io/PlantSimEngine.jl/dev/) of the doc. Is this what you expected ? If not, let me know I'll be happy to improve it further.

PS: the docs in [SpeedyWeather.jl](https://speedyweather.github.io/SpeedyWeather.jl/dev/) are down (very nice package btw, I would love to use it at some point!).

**Comment by ashiklom** [comment]
Looks great, nice work! I agree that this has been addressed.
